$packages = @(
  "Microsoft.Microsoft3DViewer"
  "Microsoft.BingSearch"
  "Microsoft.WindowsCamera"
  "Clipchamp.Clipchamp"
  "Microsoft.WindowsAlarms"
  "Microsoft.549981C3F5F10"
  "MicrosoftCorporationII.MicrosoftFamily"
  "Microsoft.WindowsFeedbackHub"
  "Microsoft.GetHelp"
  "Microsoft.Getstarted"
  "microsoft.windowscommunicationsapps"
  "Microsoft.WindowsMaps"
  "Microsoft.BingNews"
  "Microsoft.MicrosoftOfficeHub"
  "Microsoft.Office.OneNote"
  "Microsoft.OutlookForWindows"
  "Microsoft.MSPaint"
  "Microsoft.People"
  "Microsoft.PowerAutomateDesktop"
  "MicrosoftCorporationII.QuickAssist"
  "Microsoft.SkypeApp"
  "Microsoft.MicrosoftSolitaireCollection"
  "Microsoft.MicrosoftStickyNotes"
  "MSTeams"
  "Microsoft.Todos"
  "Microsoft.WindowsSoundRecorder"
  "Microsoft.Windows.DevHome"
  "Microsoft.BingWeather"
  "Microsoft.Xbox.TCUI"
  "Microsoft.XboxApp"
  "Microsoft.XboxGameOverlay"
  "Microsoft.XboxGamingOverlay"
  "Microsoft.XboxIdentityProvider"
  "Microsoft.XboxSpeechToTextOverlay"
  "Microsoft.GamingApp"
  "Microsoft.YourPhone"
  "Microsoft.OneDrive"
  "Microsoft.MicrosoftEdge"
  "Microsoft.MicrosoftEdge.Stable"
  "Microsoft.MicrosoftEdge_8wekyb3d8bbwe"
  "Microsoft.MicrosoftEdgeDevToolsClient_8wekyb3d8bbwe"
  "Microsoft.MicrosoftEdgeDevToolsClient_1000.19041.1023.0_neutral_neutral_8wekyb3d8bbwe"
  "Microsoft.MicrosoftEdge_44.19041.1266.0_neutral__8wekyb3d8bbwe"
  "Microsoft.MicrosoftEdgeDevToolsClient"
  "Microsoft.MixedReality.Portal"
  "Microsoft.Windows.Ai.Copilot.Provider"
  "Microsoft.WindowsMeetNow"
  "Microsoft.ZuneMusic"
  "Microsoft.ZuneVideo";
)

$capabilities = @(
  "Browser.InternetExplorer"
  "MathRecognizer"
  "Microsoft.Windows.Notepad"
  "Microsoft.Windows.PowerShell.ISE"
  "App.Support.QuickAssist"
  "App.StepsRecorder"
  "Media.WindowsMediaPlayer"
  "Microsoft.Windows.WordPad"
)

Get-AppxProvisionedPackage -Online | Where-Object { $packages -contains $_.DisplayName } | Remove-AppxProvisionedPackage -Online -AllUsers -ErrorAction "Continue"

Get-WindowsCapability -Online | Where-Object { $capabilities -contains $_.Name.Split("~")[0] -and $_.State -eq "Installed" } | Remove-WindowsCapability -Online -ErrorAction "Continue"